### PR TITLE
capabilities: Fix a false positive when all capabilities dropped

### LINKED ISSUE #110: False positive when all capabilities dropped
Running `kubeaudit caps` returns a lot of `ERRO[0003] Capability not dropped` messages for the pods with the following effective settings:
```yaml
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
      readOnlyRootFilesystem: true
```
From inside the container everything is clearly OK:
```
grep ^Cap /proc/1/status
CapInh:    0000000000000000
CapPrm:    0000000000000000
CapEff:    0000000000000000
CapBnd:    0000000000000000
CapAmb:    0000000000000000
```

### PR DESCRIPTION
**Pull request by jinankjain**
Fixes #110 

@Tmlja1Jldmlu hopefully this fix the false positive that you were observing.

Thanks for filing the issue. 😄

### CODE REVIEW

File: cmd/capabilities.go [hunk 1]
```diff
@@ -60,9 +60,14 @@ func recommendedCapabilitiesToBeDropped() (dropCapSet CapSet, err error) {
 func checkCapabilities(container Container, result *Result) {
 	added := CapSet{}
 	dropped := CapSet{}
+	allCapsDrop := false
 	if container.SecurityContext != nil && container.SecurityContext.Capabilities != nil {
 		added = NewCapSetFromArray(container.SecurityContext.Capabilities.Add)
-		dropped = NewCapSetFromArray(container.SecurityContext.Capabilities.Drop)
+		if len(container.SecurityContext.Capabilities.Drop) != 0 && string(container.SecurityContext.Capabilities.Drop[0]) == "all" {
```
Comment (Tmlja1Jldmlu) [inline cmd/capabilities.go]: Thanks for the quick fix!

It will be better to `strings.ToLower(string(container.SecurityContext.Capabilities.Drop[0]))`.

Unfortunately I cannot find proper refs anywhere in k8s docs or code but my tests show that this `ALL` keyword is case insensitive...
