### PR TITLE
345: Fix audit config

### LINKED ISSUE #345: Audit config does not work as documented
##### ISSUE TYPE
 - [x] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY
In the `README.md`, the example config says
```
enabledAuditors:
  # Auditors are enabled by default if they are not explicitly set to "false"
  apparmor: false
```
However, if only disabled auditors are listed, all auditors will run.

##### ENVIRONMENT
* Kubeaudit version: 0.14.1
* Kubeaudit install method: Binary

##### STEPS TO REPRODUCE

1. Create a config file:
```
enabledAuditors:
  # Auditors are enabled by default if they are not explicitly set to "false"
  apparmor: false
```
2. call `kubeaudit all -k <config from 1>`

##### EXPECTED RESULTS

All auditors, expect `apparmor` to run.

##### ACTUAL RESULTS

All auditors run, including `apparmor`.

### PR DESCRIPTION
**Pull request by genevieveluyt**
##### Description

Fixes #345 

##### Type of change

- [x] Bug fix :bug:
- [ ] New feature :sparkles:
- [ ] This change requires a documentation update :book:
- [ ] Breaking changes :warning:
##### How Has This Been Tested?

- [ ] Test A
- [ ] Test B

##### Checklist:

- [x] I have :tophat: my changes (A 🎩 specifically includes pulling down changes, setting them up, and manually testing the changed features and potential side effects to make sure nothing is broken)
- [x] I have performed a self-review of my own code
- [NA] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The test coverage did not decrease
- [NA] I have signed the appropriate [Contributor License Agreement](https://cla.shopify.com/)

### CODE REVIEW

File: auditors/all/all.go [hunk 1]
```diff
@@ -57,6 +52,17 @@ func Auditors(conf config.KubeauditConfig) ([]kubeaudit.Auditable, error) {
 	return auditors, nil
 }
 
+// getEnabledAuditors returns a list of all auditors excluding any explicitly disabled in the config
+func getEnabledAuditors(conf config.KubeauditConfig) []string {
+	auditors := []string{}
+	for _, auditorName := range AuditorNames {
+		if enabled, ok := conf.GetEnabledAuditors()[auditorName]; !ok || enabled {
```
Comment (dani-santos-code) [inline auditors/all/all.go:59]: maybe we can add a comment here to explain this line(_enabled, ok := conf.GetEnabledAuditors()[auditorName]; !ok || enabled_)?
```
// if value is not found in the `conf.GetEnabledAuditors()` map, this means
// it wasn't added to the config file, so it should be enabled by default
```

another option is to rename the var and instead of calling it enabled, call it `explicitlyEnabledInConfig`?

File: auditors/all/all_test.go [hunk 2]
```diff
@@ -97,6 +99,83 @@ func TestAllWithConfig(t *testing.T) {
...
+		{
+			testName: "Some enabled",
+			enabledAuditors: map[string]bool{
+				"apparmor": true,
+				"rootfs":   true,
+			},
+			expectedAuditors: AuditorNames,
+		},
+		{
+			// If some auditors are explicitly disabled, the rest shou;d default to being enabled
```
Comment (dani-santos-code) [inline auditors/all/all_test.go:144]: tiny thing
```suggestion
			// If some auditors are explicitly disabled, the rest should default to being enabled
```

Comment (dani-santos-code) [reply auditors/all/all_test.go:144]: The tests are really good! 👏

**Review by dani-santos-code — DISMISSED** [review]
thanks for fixing it! I tested locally with a config file and it's working as expected! :)

**Review by dani-santos-code — APPROVED** [review]

**Review by dani-santos-code — APPROVED** [review]
