### PR TITLE
Custom resource definition fix

### LINKED ISSUE #211: Support for CustomResourceDefinition workload
##### ISSUE TYPE
 - [x] Feature Idea

# BUG REPORT

##### SUMMARY

Kubeaudit doesn't parse `CustomResourceDefinition` workload.

##### ENVIRONMENT
* Kubeaudit version: 0.6.0
* Kubeaudit install method: -

##### STEPS TO REPRODUCE

```sh
kubeaudit all -f followingfile.yml
```
##### EXPECTED RESULTS

kubeaudit should warn unsupported resource `CustomResourceDefinition`

##### ACTUAL RESULTS

Errors out with `Invalid kubernetes workload`

```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wgnodes.wormhole.gravitational.io
spec:
  group: wormhole.gravitational.io
  names:
    kind: Wgnode
    plural: wgnodes
  scope: Namespaced
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```

### PR DESCRIPTION
**Pull request by r6min**
##### Description

Fixes #211

Changes:

- Added support for parsing of CustomResourceDefinition objects by adding the decoding schema to the apiextensions module which contains the CustomResourceDefinition
- Updated the client-go module version for Kubernetes (k8s.io/client-go) to use the stable version instead of master, fixing an issue with a rest request. Source: https://www.henryxieblogs.com/2019/04/errorrequestgo59831-not-enough.html?fbclid=IwAR3czQ3oIVtb9UWYF01TxIJOWAC_iJuP3tdwEt0VdHAzdV6jUGJV1LAZg7A  
- Refactored the code that checks if the object's Group Version Kind is supported by using a set, making the supported list modular and reusable 
- Added a basic unit test to cover the new CRD functionality.

##### Type of change

- [✓] Bug fix :bug:
- [ ] New feature :sparkles:
- [ ] This change requires a documentation update :book:
- [ ] Breaking changes :warning:
##### How Has This Been Tested?

- [✓] Added unit test for the getKubeResourcesManifest function for the CustomResourceDefinition type
- [✓] End-to-end test using the kubeaudit CLI tool and the YAML file included in the issue description
- [✓] Regression tests passing

##### Checklist:

- [✓ ] I have :tophat: my changes (A 🎩 specifically includes pulling down changes, setting them up, and manually testing the changed features and potential side effects to make sure nothing is broken)
- [✓ ] I have performed a self-review of my own code
- [✓ ] I have made corresponding changes to the documentation
- [✓ ] I have added tests that prove my fix is effective or that my feature works
- [✓ ] New and existing unit tests pass locally with my changes
- [✓ ] The test coverage did not decrease

### CODE REVIEW

File: cmd/types.go [hunk 1]
```diff
@@ -105,6 +105,23 @@ type Metadata = map[string]string
 // UnsupportedType is a type alias for v1 version of the k8s apps API, this is meant for testing
 type UnsupportedType = apiv1.Binding
 
+// Resource types listed here
+var resourceTypes = map[string]bool{"ReplicaSet" : true, "Endpoints" : true, "Ingress" : true, "Service" : true,
```
Comment (nschhina) [inline cmd/types.go]: I think it's better if we rename this to `ResourceTypes` as we should be exporting this map.

File: cmd/util_test.go [hunk 2]
```diff
@@ -51,3 +50,11 @@ func TestCertificateResourceV1(t *testing.T) {
...
 	assert.NotNil(warn)
 }
+
+func TestCustomResourceDefinition(t *testing.T){
+	file := "../fixtures/custom_resource_definition.yml"
+	assert := assert.New(t)
+	resources, err := getKubeResourcesManifest(file)
+	assert.Nil(err)
+	assert.Len(resources, 1)
+}
```
Comment (nschhina) [inline cmd/util_test.go]: Please ensure you end all files with newline as many Unix tools don't behave properly with files not ending with newline chars.

File: fixtures/custom_resource_definition.yml [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+    plural: wgnodes
+  scope: Namespaced
+  version: v1beta1
+status:
+  acceptedNames:
+    kind: ""
+    plural: ""
+  conditions: []
+  storedVersions: []
+
```
Comment (nschhina) [inline fixtures/custom_resource_definition.yml]: This still isn't correct, please check the newline

File: cmd/types.go [hunk 4]
```diff
@@ -105,6 +105,23 @@ type Metadata = map[string]string
 // UnsupportedType is a type alias for v1 version of the k8s apps API, this is meant for testing
 type UnsupportedType = apiv1.Binding
 
+// Resource types listed here
```
Comment (nschhina) [inline cmd/types.go]: `// ResourceTypes is a map of all the Kubernetes workloads kubeaudit can decode`

export comments should start with the variable name, in this case `ResourceTypes`
