### PR TITLE
Fix golint

### LINKED ISSUE #55: Make golint happy
https://goreportcard.com/report/github.com/Shopify/kubeaudit#golint

### PR DESCRIPTION
**Pull request by genevieveluyt**
Fixes #55 . This PR fixes linter warnings by adding comments and renaming variables.

### CODE REVIEW

**Comment by klautcomputing** [comment]
I am on vacation right now, somewhere in the wilderness of BC. I gave it a really quick look on my phone but defer to @jinankjain for an actual and meaningful review :)

File: cmd/readOnlyRootFilesystem_test.go [hunk 1]
```diff
@@ -2,12 +2,12 @@ package cmd
 
 import "testing"
 
-func TestSecurityContextNIL_RORF(t *testing.T) {
-	runAuditTest(t, "security_context_nil.yml", auditReadOnlyRootFS, []int{ErrorReadOnlyRootFilesystemNIL})
+func TestSecurityContextNil_RORF(t *testing.T) {
```
Comment (jinankjain) [inline cmd/readOnlyRootFilesystem_test.go]: Just a minor nit you can remove '_' as well since the camelCase is good enough :)

File: cmd/types.go [hunk 2]
```diff
@@ -11,44 +11,86 @@ import (
...
+// NetworkPolicyList represents the same type from the v1 version of the k8s API.
 type NetworkPolicyList = networking.NetworkPolicyList
+
+// PodList represents the same type from the v1 version of the k8s API.
 type PodList = apiv1.PodList
+
+// ReplicationControllerList represents the same type from the v1 version of the k8s API.
 type ReplicationControllerList = apiv1.ReplicationControllerList
+
+// StatefulSetList represents the same type from the v1beta1 version of the k8s API.
```
Comment (jinankjain) [inline cmd/types.go]: Better wording: StatefulSetList is a type alias for v1beta1 version of the k8s API. Same goes for rest of them.
