### PR TITLE
Audit all containers

### LINKED ISSUE #141: Autofix broken for multiple containers
When autofixing

```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cababilitiesAdded
  namespace: fakeDeploymentSC
spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        apps: fakeSecurityContext
    spec:
      containers:
      - name: fakeContainerSC1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - AUDIT_WRITE
      - name: fakeContainerSC2
```
The resulting YAML is
```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cababilitiesAdded
  namespace: fakeDeploymentSC
spec:
  selector: null
  strategy: {}
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/fakeContainerSC1: runtime/default
        container.apparmor.security.beta.kubernetes.io/fakeContainerSC2: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      creationTimestamp: null
      labels:
        apps: fakeSecurityContext
    spec:
      automountServiceAccountToken: false
      containers:
      - name: fakeContainerSC1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - NET_RAW
            - SETFCAP
            - SETGID
            - SETPCAP
            - SETUID
            - SYS_CHROOT
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      - name: fakeContainerSC2
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - NET_RAW
            - SETFCAP
            - SETGID
            - SETPCAP
            - SETUID
            - SYS_CHROOT
status: {}
```
which has
```
privileged: false
readOnlyRootFilesystem: true
runAsNonRoot: true
```
added for the first container but not the second. The example above is actually the test file `fixtures/autofix_v1.yml`. It tests against the expected output `fixtures/autofix-fixed_v1.yml`. The expected output has
```
privileged: false
readOnlyRootFilesystem: true
runAsNonRoot: true
```
for both containers yet the test still passes...

### PR DESCRIPTION
**Pull request by klautcomputing**
This fixes #141 

Turns out if you `break` out of your loop then you never get shit done 🙂 

Added a regression test. Turns out: deep equal from `deep` doesn't catch the difference, deep equal from `reflect` complains that they are not equal, so I serialize them, write them to file and compare the file contents.

### CODE REVIEW

File: cmd/autofix_test.go [hunk 1]
```diff
@@ -1,13 +1,49 @@
...
+	if err != nil {
+		return false
+	}
+
+	s1 := bufio.NewScanner(f1)
+	s2 := bufio.NewScanner(f2)
+
+	for s1.Scan() {
+		s2.Scan()
+		if !bytes.Equal(s1.Bytes(), s2.Bytes()) {
```
Comment (genevieveluyt) [inline cmd/autofix_test.go]: I'm sure this is more efficient but would it be more convenient for debugging to compare strings so that if the test fails it is easy to see the difference?

File: cmd/autofix_test.go [hunk 2]
```diff
@@ -1,13 +1,49 @@
...
+			return false
+		}
+	}
+	return true
+}
+
+func assertEqualWorkloads(assert *assert.Assertions, resource1, resource2 []Resource) {
+	file1 := "/tmp/dat1"
```
Comment (genevieveluyt) [inline cmd/autofix_test.go]: Would it be beneficial to use io.ioutil.TempFile on the off chance that this file name is used by another program?

File: cmd/autofix_test.go [hunk 3]
```diff
@@ -1,13 +1,49 @@
...
+	"bytes"
+	"os"
 	"testing"
 
 	"github.com/stretchr/testify/assert"
-
-	"github.com/go-test/deep"
 )
 
+func compareFiles(file1, file2 string) bool {
```
Comment (genevieveluyt) [inline cmd/autofix_test.go]: +1 I will use this function in my PR :D

File: cmd/autofix_test.go (hunk 1 above)
Comment (klautcomputing) [reply cmd/autofix_test.go]: Changed it to `.Text()` and added a `printf` for it so that you get notified about the difference.

File: cmd/test_util.go [hunk 4]
```diff
@@ -112,3 +116,29 @@ func assertEqualYaml(fileToFix string, fileFixed string, auditFunc func(resource
 	assert.Nil(err)
 	assert.Equal(correctlyFixedResources[0], fixedResource)
 }
+
+// WriteToTmpFile writes a single resource to a tmpfile, you are responsible
+// for closing the file afterwards, that's why the function returns the file
```
Comment (genevieveluyt) [inline cmd/test_util.go]: Just nitpicking, do you mean deleting the file? It looks like it is closed on line 139 `err = tmpfile.Close()`

File: cmd/autofix_test.go [hunk 5]
```diff
@@ -1,13 +1,50 @@
...
+	"fmt"
+	"os"
 	"testing"
 
 	"github.com/stretchr/testify/assert"
-
-	"github.com/go-test/deep"
 )
 
+func compareFiles(file1, file2 string) bool {
```
Comment (chrisdonaldson) [inline cmd/autofix_test.go]: Is it worth being explicit that this only safely compares text files and will ignore EOL characters? (`\r?\n`)

File: cmd/test_util.go [hunk 6]
```diff
@@ -112,3 +116,29 @@ func assertEqualYaml(fileToFix string, fileFixed string, auditFunc func(resource
...
+	if err != nil {
+		return "", err
+	}
+	_, err = tmpfile.Write(yaml)
+	if err != nil {
+		return "", err
+	}
+	err = tmpfile.Close()
+	if err != nil {
+		return "", err
```
Comment (chrisdonaldson) [inline cmd/test_util.go]: Why return an empty string on failed `.Close?` or write calls? Makes sense to me on open but in theory the filename might be useful to output on error by the caller?

File: cmd/autofix_test.go (hunk 5 above)
Comment (klautcomputing) [reply cmd/autofix_test.go]: Why does this only safely compare text files? And why do you say it ignores EOL characters?

File: cmd/test_util.go (hunk 6 above)
Comment (klautcomputing) [reply cmd/test_util.go]: There are only 2 cases in which an error can occur for a `file.Close()`, iirc. And correct me if I am wrong:
1. The file handle is `nil`. This would mean something super weird has happened because no other program should have the file handle because we just created it and this is single threaded so I don't see how it could have been `nil`.
1. The file has already be closed. If this is the case you already get an error that contains the filename in its error message.

So I cannot see the first one happen and for the second one you already get an informative error message.

Comment (chrisdonaldson) [reply cmd/test_util.go]: 👍

File: cmd/autofix_test.go (hunk 5 above)
Comment (chrisdonaldson) [reply cmd/autofix_test.go]: `NewScanner` defaults to `ScanLines`. I'm still pretty new to this go jazz but `ScanLines` tries to drop carriage returns and newlines. The source seems to agree with my remembering: https://golang.org/src/bufio/scan.go?s=11799:11877#L345. 

If a non-text file is compared it would drop a bunch of probably meaningful, if misunderstood, bytes. It's a pretty unlikely situation where you end up with a false positive there in non-trivial cases I suppose.
