### PR TITLE
✨ Adds "deprecated apis" auditor

### LINKED ISSUE #408: Deprecated API auditor
##### ISSUE TYPE
 - [ ] Bug Report
 - [x] Feature Idea

##### SUMMARY
The idea is to create a new auditor that'll check for deprecated api versions of resources. Suggested by @jerr

### PR DESCRIPTION
**Pull request by jerr**
##### Description
Fixes #408

Adds a new command `deprecatedapis` to find deprecated APIs of resources. It reports for all resources defined with a deprecated API the version since when it is deprecated  the deprecated version, the version where is removed and suggests the recommended API.

Here's a sample result:

```
$ kubeaudit deprecatedapis -f "auditors/deprecatedapis/fixtures/cronjob.yml"

---------------- Results for ---------------
  apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: hello
--------------------------------------------
-- [warning] DeprecatedAPIUsed
   Message: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
   Metadata:
      DeprecatedMajor: 1
      DeprecatedMinor: 21
      RemovedMajor: 1
      RemovedMinor: 25
      ReplacementKind: CronJob
      ReplacementGroup: batch/v1
```

This PR also brings the possibility to audit any type of resource using the [dynamic client](https://github.com/kubernetes/client-go/tree/master/examples/dynamic-create-update-delete-deployment#create-update--delete-deployment-with-the-dynamic-package).   

##### Type of change

- [x] New feature :sparkles:
- [x] This change requires a documentation update :book:

##### How Has This Been Tested?

- [x] Automated tests 
- [x] Manual tests (local mode and manifest files)

##### Checklist:

- [x] I have :tophat: my changes (A 🎩 specifically includes pulling down changes, setting them up, and manually testing the changed features and potential side effects to make sure nothing is broken)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The test coverage did not decrease
- [x] I have signed the appropriate [Contributor License Agreement](https://cla.shopify.com/)

### CODE REVIEW

**Comment by jerr** [comment]
👆 rebased on the `mani` branch

File: internal/k8sinternal/client.go [hunk 1]
```diff
@@ -65,6 +65,9 @@ func NewKubeClientLocal(configPath string) (KubeClient, error) {
 		return nil, err
 	}
 
+	// Ignore warnings from kubeclient as they are expected to be reported by the deprecatedapi auditor.
+	kubeconfig.WarningHandler = rest.NoWarnings{}
+
```
Comment (jerr) [inline internal/k8sinternal/client.go:70]: This  will hide warning messages such as the following:
```
W0608 12:04:51.010357   30221 warnings.go:70] v1 ComponentStatus is deprecated in v1.19+
W0608 12:04:54.355517   30221 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

Kubeaudit has to use the deprecated APIs to include them in the deprecatedapis reports.  
See https://kubernetes.io/blog/2020/09/03/warnings/#customize-client-handling

File: docs/auditors/deprecatedapis.md [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+   Metadata:
+      DeprecatedMajor: 1
+      DeprecatedMinor: 21
+      RemovedMajor: 1
+      RemovedMinor: 25
+      ReplacementKind: CronJob
+      ReplacementGroup: batch/v1
+```
+
+The `deprecatedapis` auditor can be used `--targeted-k8s-version` flag. If the API is not yet deprecated for this version the auditor will produce an `info` otherwise a `warning`.
```
Comment (genevieveluyt) [inline docs/auditors/deprecatedapis.md:46]:
```suggestion
The `deprecatedapis` auditor can be used with the `--targeted-k8s-version` flag. If the API is not yet deprecated for this version the auditor will produce an `info` otherwise a `warning`.
```

File: docs/auditors/deprecatedapis.md [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+
+```
+kubeaudit deprecatedapis [flags]
+```
+
+### Flags
+| Short   | Long                   | Description                                   | Default             |
+| :------ | :--------------------- | :-------------------------------------------- | :------------------ |
+|         | --current-k8s-version  | Kubernetes current version                    |                     |
+|         | --targeted-k8s-version | Kubernetes version to migrate to              |                     |
```
Comment (genevieveluyt) [inline docs/auditors/deprecatedapis.md:15]: I'm a bit unclear why there is a flag for both current and target version. Maybe I'm misunderstanding the use case, but to me it sounds easier to reason about if we had just the target version:

- `ERROR` if the resource API is removed in the target version
- `WARN` if the resource API is deprecated in the target version
- `INFO` if the resource API is not deprecated in the target version but will be deprecated in a future version

We could default to the current version in local and cluster mode since kubeaudit should be able to look that up automatically?

**Review by genevieveluyt — COMMENTED** [review]
No major concerns though I would like to put this in the next release, so will approve / merge when the current release it out!

File: docs/auditors/deprecatedapis.md (hunk 3 above)
Comment (jerr) [reply docs/auditors/deprecatedapis.md:15]: If we specify a `current version` or this information is retrieved from the cluster without a targeted version we can have the following cases:
- `ERROR` if the resource API is removed in the current version
- `WARN` if the resource API is deprecated in the current version
- `INFO` if the resource API is not deprecated in the current version but will be deprecated in a future version

If we use a targeted version the message level takes precedence over the current version.

But maybe we can remove this option and only use the current version in the local or in cluster mode 🤔

Comment (genevieveluyt) [reply docs/auditors/deprecatedapis.md:15]: Ah I see from your flag description

```
--targeted-k8s-version string   Kubernetes version to migrate to (eg 1.24)
```
The use case for this auditor is for doing Kubernetes version migrations?

Based on the description of the auditor "This command determines which resource is defined with a deprecated API version." I was thinking of "target version" as "check Kubernetes resources against this version", hence it didn't make sense to me to have both "current" and "target" versions. Did you have a specific workflow in mind where you would benefit from passing both current and target versions (eg. running against a live cluster as a one-off before doing a migration)? If so, I think we should document it (eg. as an example) to make the use of the flags more clear. Nothing (other than the target flag description) says anything about migrations.

Comment (jerr) [reply docs/auditors/deprecatedapis.md:15]: Many APIs have been declared deprecated since the 1.16 but are removed from the version 1.22.  If the current version is before the 1.16 we can keep the API as it is but  if it is not the case, it is better to migrate the API as soon as possible. That is why a warning is generated from the version 1.16.

But as currently `kubeaudit` does not retrieve  the current version from the cluster we can remove this option in a first time.

**Review by genevieveluyt — DISMISSED** [review]

**Review by genevieveluyt — APPROVED** [review]
